MajorProjectY4/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views as user_views
from prod.views import BootstrapFilterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('prod.urls'), name='bootstrap'),
    path('register/', user_views.register, name='register'),
    path('prof123/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('products.urls', namespace='products')),
    path('', include('shopping_cart.urls', namespace='shopping_cart')),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views
from prod.views import BootstrapFilterView
from products.views import product_list
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView


urlpatterns = [
    path('', views.home, name='app-home'),
    path('about/', views.about, name='about-page'),
    path('appliances/', views.appliances, name='app-page'),
    path('productsNew/', views.productsNew, name='app-product'),
    path('profile/', PostListView.as_view(), name='app-profile'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('bootstrap_form/', BootstrapFilterView, name='bootstrap-form'),
    path('products/', product_list, name='product-list')
]

products/urls.py
from django.conf.urls import url

from .views import product_list

app_name = 'products'

urlpatterns = [
    url('products/', product_list, name='product-list')
]

shopping_cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=120)
    price = models.IntegerField()

    def __str__(self):
        return self.name

products/views.py
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from shopping_cart.models import Order
from .models import Product

@login_required
def product_list(request):
    object_list = Product.objects.all()
    filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
    current_order_products = []
    if filtered_orders.exists():
    	user_order = filtered_orders[0]
    	user_order_items = user_order.items.all()
    	current_order_products = [product.product for product in user_order_items]

    context = {
        'object_list': object_list,
        'current_order_products': current_order_products
    }

    return render(request, "products/product_list.html", context)

products/templates/products/product_list.html
{% extends 'app/base.html' %}
{% block content %}
<h2>List of items</h2>

    {{ message }}
    <div class="row">
    {% for object in object_list %}
    <div class="col-md-6 mb-4">
    
        <img src="https://brain-images-ssl.cdn.dixons.com/2/4/10180942/u_10180942.jpg" class="img-fluid" alt="">

      </div>
        <div class="col-sm-3">
            <p>{{ object.name }}</p>
            <p>Price: €{{ object.price }}</p>
            {% if object in user.profile.ebooks.all %}
            <!-- add a button here to see the product -->
            You own this
            {% elif object in current_order_products %}
            <a href="{% url 'shopping_cart:order_summary' %}" class="btn btn-warning">Go to Cart</a>
            {% else %}
            <a href="{% url 'shopping_cart:add_to_cart' object.id %}" class="btn btn-warning">Add to Cart</a>
            {% endif %}
        </div>
    {% endfor %}
    </div>

{% endblock content %}